# logfile                                    mode count size  when  flags
/Users/__USER__/.haystack/launchd-server.log 644  4     1024  $W0   J
/Users/__USER__/.haystack/launchd-hourly.log 644  4     1024  $W0   J
